/**
 * Phase 1 1E/1F: Full-paper workspace.
 *
 * Renders the persisted full-paper artifact (Phase 1 1C) with an explicit
 * state machine, the paper-level evaluation (scope=paper, distinct from the
 * proposal evaluation), citation status, and Markdown/LaTeX/BibTeX export
 * controls that call the dedicated paper-export endpoints.
 *
 * Truth rules (WP-1C/1D/1E/1F):
 *  - proposal and paper are visibly distinct (this is the Paper tab)
 *  - an empty/placeholder paper never appears as ready
 *  - paper evaluation is labeled "Paper evaluation", never collapsed with
 *    proposal evaluation
 *  - a failed evaluator does not block viewing/exporting a generated paper
 *  - each non-ready state shows an actionable message
 *  - exports operate on the final paper only; 404 handled explicitly
 */
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Download, FileText, AlertCircle, Loader2, CheckCircle2 } from "lucide-react";
import { toast } from "sonner";
import type { PaperArtifact } from "@/api/types";
import {
  exportPaperMarkdown,
  exportPaperLatex,
  exportPaperBibtex,
} from "@/api/exports";

function triggerBlobDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function safeFilename(title: string | null, ideaId: number, ext: string) {
  const base = title ? title.replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_+|_+$/g, "").slice(0, 60) : `paper`;
  return `${base || "paper"}--idea-${ideaId}.${ext}`;
}

interface PaperWorkspaceProps {
  ideaId: number;
  paper: PaperArtifact | null;
  unresolvedCitationCount: number | null;
}

export function PaperWorkspace({ ideaId, paper, unresolvedCitationCount }: PaperWorkspaceProps) {
  const [busy, setBusy] = useState<null | "md" | "latex" | "bibtex">(null);

  if (!paper || paper.status === "not_requested") {
    return (
      <Card>
        <CardContent className="py-10 text-center text-muted-foreground">
          <FileText className="mx-auto mb-3 h-8 w-8 opacity-50" />
          <p className="text-sm">
            No full paper was requested for this run. Full papers are generated by
            the <strong>deep_research</strong> and <strong>academic_proposal</strong>{" "}
            strategies.
          </p>
        </CardContent>
      </Card>
    );
  }

  if (paper.status === "pending") {
    return (
      <Card>
        <CardContent className="py-10 text-center text-muted-foreground">
          <Loader2 className="mx-auto mb-3 h-8 w-8 animate-spin opacity-70" />
          <p className="text-sm">
            Full paper is pending. Paper synthesis runs after proposal synthesis
            and evaluation; it will appear here once the run completes.
          </p>
        </CardContent>
      </Card>
    );
  }

  if (paper.status === "failed") {
    return (
      <Card>
        <CardContent className="py-10 text-center">
          <AlertCircle className="mx-auto mb-3 h-8 w-8 text-destructive" />
          <p className="text-sm font-medium text-destructive">Paper generation failed.</p>
          <p className="mt-1 text-xs text-muted-foreground">
            The paper stage ran but produced an empty or failed artifact. You can
            still view and export the proposal, or re-run with a different strategy.
          </p>
        </CardContent>
      </Card>
    );
  }

  // status === "ready"
  async function handleExport(format: "md" | "latex" | "bibtex") {
    setBusy(format);
    try {
      const title = paper?.title ?? null;
      if (format === "md") {
        const blob = await exportPaperMarkdown(ideaId);
        triggerBlobDownload(blob, safeFilename(title, ideaId, "md"));
      } else if (format === "latex") {
        const blob = await exportPaperLatex(ideaId);
        triggerBlobDownload(blob, safeFilename(title, ideaId, "tex"));
      } else {
        const blob = await exportPaperBibtex(ideaId);
        triggerBlobDownload(blob, safeFilename(title, ideaId, "bib"));
      }
      toast.success(`Paper exported as ${format === "md" ? "Markdown" : format === "latex" ? "LaTeX" : "BibTeX"}`);
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Export failed";
      toast.error(msg);
    } finally {
      setBusy(null);
    }
  }

  const evaluation = paper.paper_evaluation;

  return (
    <div className="space-y-6">
      {/* Paper header + meta */}
      <Card>
        <CardHeader className="pb-3">
          <div className="flex items-start justify-between gap-4">
            <div className="space-y-1">
              <CardTitle className="text-base flex items-center gap-2">
                <FileText className="h-4 w-4" />
                Full Research Paper
              </CardTitle>
              {paper.title && <p className="text-sm text-muted-foreground">{paper.title}</p>}
            </div>
            <Badge variant="secondary" className="gap-1">
              <CheckCircle2 className="h-3 w-3" /> Ready
            </Badge>
          </div>
        </CardHeader>
        <CardContent className="text-xs text-muted-foreground">
          <div className="flex flex-wrap gap-x-6 gap-y-1">
            {paper.word_count != null && <span>{paper.word_count.toLocaleString()} words</span>}
            {paper.source_count != null && <span>{paper.source_count} sources</span>}
            {paper.synthesis_strategy && <span>strategy: {paper.synthesis_strategy}</span>}
            {paper.model_used && <span>model: {paper.model_used}</span>}
            {paper.generated_at && <span>generated: {new Date(paper.generated_at).toLocaleString()}</span>}
            {paper.source_run_id != null && <span>run #{paper.source_run_id}</span>}
          </div>
        </CardContent>
      </Card>

      {/* Export controls (1F) */}
      <div className="flex flex-wrap items-center gap-2">
        <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
          Export paper:
        </span>
        <Button variant="outline" size="sm" disabled={busy !== null} onClick={() => handleExport("md")}>
          {busy === "md" ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Download className="mr-2 h-4 w-4" />}
          Markdown
        </Button>
        <Button variant="outline" size="sm" disabled={busy !== null} onClick={() => handleExport("latex")}>
          {busy === "latex" ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Download className="mr-2 h-4 w-4" />}
          LaTeX
        </Button>
        <Button variant="outline" size="sm" disabled={busy !== null} onClick={() => handleExport("bibtex")}>
          {busy === "bibtex" ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Download className="mr-2 h-4 w-4" />}
          BibTeX
        </Button>
      </div>

      {/* Paper content */}
      {paper.paper_md && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm">Paper Content</CardTitle>
          </CardHeader>
          <CardContent>
            <pre className="max-h-[600px] overflow-auto whitespace-pre-wrap rounded-md bg-muted/40 p-4 font-mono text-xs leading-relaxed">
              {paper.paper_md}
            </pre>
          </CardContent>
        </Card>
      )}

      {/* Paper-level evaluation (1D) — scope labeled explicitly */}
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm flex items-center gap-2">
            Paper Evaluation
            <Badge variant="outline">scope: paper</Badge>
          </CardTitle>
        </CardHeader>
        <CardContent className="text-xs">
          {!evaluation || evaluation.status === "unavailable" ? (
            <p className="text-muted-foreground">Paper evaluation unavailable (no non-empty paper was evaluated).</p>
          ) : evaluation.status === "failed" ? (
            <div className="flex items-start gap-2 text-destructive">
              <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />
              <div>
                <p className="font-medium">Paper evaluation failed.</p>
                <p className="text-muted-foreground">
                  The paper itself generated successfully and can still be viewed and exported. {evaluation.error}
                </p>
              </div>
            </div>
          ) : evaluation.dimensions ? (
            <div className="space-y-2">
              <p className="text-muted-foreground">
                Evaluated object: final paper. These scores are distinct from the proposal
                evaluation shown on the Proposal tab.
              </p>
              <div className="grid gap-2 sm:grid-cols-2">
                {Object.entries(evaluation.dimensions).map(([dim, val]) => {
                  const v = val as { score?: number; justification?: string };
                  return (
                    <div key={dim} className="rounded-md border p-2">
                      <div className="flex items-center justify-between">
                        <span className="font-medium capitalize">{dim}</span>
                        {typeof v.score === "number" && (
                          <Badge variant="secondary">{(v.score as number).toFixed(2)}</Badge>
                        )}
                      </div>
                      {v.justification && (
                        <p className="mt-1 text-muted-foreground">{v.justification}</p>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          ) : (
            <p className="text-muted-foreground">No evaluation dimensions present.</p>
          )}
        </CardContent>
      </Card>

      {/* Citation status */}
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm">Citation Status</CardTitle>
        </CardHeader>
        <CardContent className="text-xs text-muted-foreground">
          {unresolvedCitationCount == null ? (
            <p>Citation audit not available for this paper.</p>
          ) : unresolvedCitationCount === 0 ? (
            <span className="flex items-center gap-2 text-emerald-600">
              <CheckCircle2 className="h-4 w-4" /> All references resolved.
            </span>
          ) : (
            <span className="flex items-center gap-2 text-amber-600">
              <AlertCircle className="h-4 w-4" /> {unresolvedCitationCount} unresolved reference
              {unresolvedCitationCount === 1 ? "" : "s"} — see the Proposal tab for details.
            </span>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
