"""
Pipeline-wide constants.

Single source of truth for shared values used across pipeline stages.
"""

# AI Honesty Badge — appended to all exported proposals and papers.
# Defined once, reused everywhere (A-05).
AI_HONESTY_BADGE: str = (
    "\n\n---\n\n"
    "*This research proposal was generated by an AI pipeline. "
    "Claims should be independently verified.*\n"
)

AI_HONESTY_BADGE_BRIEF: str = (
    "This research proposal was generated by an AI pipeline. "
    "Claims should be independently verified."
)
