"""Production-path dual probe suite (P0.4A1.4).

Runs two document probes and one query probe through the canonical
``GovernedEmbeddingAdapter`` so the check exercises the exact production
path rather than duplicating it.

The probe validates:
  - document result count correct
  - query result present
  - document dimensions consistent and match expected
  - query dimension matches document dimension
  - observed dimension matches profile
  - identity evidence does not conflict across roles
  - normalization/post-processing contract satisfied

Probe vectors are NOT persisted — they are ephemeral health-check
artifacts, not corpus data.

Probe suite version: ``EMBEDDING_PROBE_SUITE_V1``. Changing the probes
must not silently reuse evidence generated by an older suite.

Frozen rule:
  A failed or incomplete probe may create check evidence, but it may
  never create a resolved capability binding.
"""

from __future__ import annotations

import logging
import math
from dataclasses import dataclass
from typing import Any

from backend.pipeline.governed_embedding_adapter import GovernedEmbeddingAdapter
from backend.pipeline.governed_embedding_adapter import GovernedEmbeddingAdapterError
from backend.pipeline.knowledge.embedding_provider_identity import (
    ProviderModelIdentityEvidence,
)
from backend.pipeline.vector_contracts import EMBEDDING_PROBE_SUITE_V1

logger = logging.getLogger(__name__)

# ── Probe suite ───────────────────────────────────────────────────────

_DOCUMENT_PROBES = [
    "capability-probe-document-alpha",
    "capability-probe-document-beta",
]
_QUERY_PROBE = "capability-probe-query"


@dataclass(frozen=True)
class CapabilityProbeResult:
    """Result of a capability dual-probe.

    On pass: all observation fields populated, failure fields NULL.
    On fail: failure fields populated, observation fields NULL.
    """

    passed: bool
    observed_document_dimension: int | None
    observed_query_dimension: int | None
    observed_document_norm_min: float | None
    observed_document_norm_max: float | None
    observed_query_norm: float | None
    document_evidence: ProviderModelIdentityEvidence | None
    query_evidence: ProviderModelIdentityEvidence | None
    failure_category: str | None
    failure_code: str | None
    sanitized_error_detail: str | None


def _sanitize_detail(detail: str) -> str:
    """Strip credentials and truncate to 500 chars."""
    import re
    # Strip userinfo
    detail = re.sub(r"\w+:\w+@", "[creds]@", detail)
    # Strip api_key=, token=, etc.
    detail = re.sub(
        r"(api_key|token|secret|password|bearer)\s*=\s*\S+",
        "[auth]",
        detail,
        flags=re.IGNORECASE,
    )
    return detail[:500]


def _vector_norm(vec: tuple[float, ...]) -> float:
    """L2 norm of a vector."""
    return math.sqrt(sum(v * v for v in vec))


def _norms_range(vectors: tuple[tuple[float, ...], ...]) -> tuple[float, float]:
    """Return (min_norm, max_norm) across a batch of vectors."""
    norms = [_vector_norm(v) for v in vectors]
    return min(norms), max(norms)


async def probe_embedding_capability(
    adapter: GovernedEmbeddingAdapter,
    expected_dimension: int,
) -> CapabilityProbeResult:
    """Run a dual-probe: 2 document probes + 1 query probe.

    Exercises the production adapter path (``embed_documents_with_evidence``
    and ``embed_query_with_evidence``), validates the output, and captures
    identity evidence.

    Returns a ``CapabilityProbeResult``. On pass, all observation fields
    are populated. On fail, failure fields are populated and observations
    are NULL.
    """
    try:
        # ── Document probe ──
        doc_vectors, doc_evidence = await adapter.embed_documents_with_evidence(
            _DOCUMENT_PROBES
        )

        if len(doc_vectors) != len(_DOCUMENT_PROBES):
            return CapabilityProbeResult(
                passed=False,
                observed_document_dimension=None,
                observed_query_dimension=None,
                observed_document_norm_min=None,
                observed_document_norm_max=None,
                observed_query_norm=None,
                document_evidence=None,
                query_evidence=None,
                failure_category="probe_result_count",
                failure_code="document_probe_count_mismatch",
                sanitized_error_detail=(
                    f"document probe returned {len(doc_vectors)} vectors, "
                    f"expected {len(_DOCUMENT_PROBES)}"
                )[:500],
            )

        doc_dim = len(doc_vectors[0]) if doc_vectors else 0
        doc_norm_min, doc_norm_max = _norms_range(doc_vectors)

        # ── Query probe ──
        query_vector, query_evidence = await adapter.embed_query_with_evidence(
            _QUERY_PROBE
        )

        if not query_vector:
            return CapabilityProbeResult(
                passed=False,
                observed_document_dimension=None,
                observed_query_dimension=None,
                observed_document_norm_min=None,
                observed_document_norm_max=None,
                observed_query_norm=None,
                document_evidence=None,
                query_evidence=None,
                failure_category="probe_result_empty",
                failure_code="query_probe_empty",
                sanitized_error_detail="query probe returned empty vector",
            )

        query_dim = len(query_vector)
        query_norm = _vector_norm(query_vector)

        # ── Cross-validation ──

        # Dimension consistency: document dims must match each other
        for i, v in enumerate(doc_vectors):
            if len(v) != doc_dim:
                return CapabilityProbeResult(
                    passed=False,
                    observed_document_dimension=None,
                    observed_query_dimension=None,
                    observed_document_norm_min=None,
                    observed_document_norm_max=None,
                    observed_query_norm=None,
                    document_evidence=None,
                    query_evidence=None,
                    failure_category="probe_dimension_inconsistency",
                    failure_code="document_dimension_variance",
                    sanitized_error_detail=(
                        f"document probe vector {i} has dim {len(v)}, "
                        f"expected {doc_dim}"
                    )[:500],
                )

        # Query dimension must match document dimension
        if query_dim != doc_dim:
            return CapabilityProbeResult(
                passed=False,
                observed_document_dimension=doc_dim,
                observed_query_dimension=query_dim,
                observed_document_norm_min=doc_norm_min,
                observed_document_norm_max=doc_norm_max,
                observed_query_norm=query_norm,
                document_evidence=doc_evidence,
                query_evidence=query_evidence,
                failure_category="probe_dimension_mismatch",
                failure_code="query_document_dimension_mismatch",
                sanitized_error_detail=(
                    f"query dim {query_dim} != document dim {doc_dim}"
                )[:500],
            )

        # Observed dimension must match expected (profile) dimension
        if doc_dim != expected_dimension:
            return CapabilityProbeResult(
                passed=False,
                observed_document_dimension=doc_dim,
                observed_query_dimension=query_dim,
                observed_document_norm_min=doc_norm_min,
                observed_document_norm_max=doc_norm_max,
                observed_query_norm=query_norm,
                document_evidence=doc_evidence,
                query_evidence=query_evidence,
                failure_category="probe_dimension_mismatch",
                failure_code="observed_vs_expected_dimension_mismatch",
                sanitized_error_detail=(
                    f"observed dim {doc_dim} != expected {expected_dimension}"
                )[:500],
            )

        # Identity evidence must not conflict across roles
        # (same provider_kind and requested_model)
        if doc_evidence.provider_kind != query_evidence.provider_kind:
            return CapabilityProbeResult(
                passed=False,
                observed_document_dimension=doc_dim,
                observed_query_dimension=query_dim,
                observed_document_norm_min=doc_norm_min,
                observed_document_norm_max=doc_norm_max,
                observed_query_norm=query_norm,
                document_evidence=doc_evidence,
                query_evidence=query_evidence,
                failure_category="probe_evidence_conflict",
                failure_code="provider_kind_conflict",
                sanitized_error_detail=(
                    f"document provider_kind={doc_evidence.provider_kind!r} "
                    f"!= query provider_kind={query_evidence.provider_kind!r}"
                )[:500],
            )

        # ── Pass ──
        return CapabilityProbeResult(
            passed=True,
            observed_document_dimension=doc_dim,
            observed_query_dimension=query_dim,
            observed_document_norm_min=doc_norm_min,
            observed_document_norm_max=doc_norm_max,
            observed_query_norm=query_norm,
            document_evidence=doc_evidence,
            query_evidence=query_evidence,
            failure_category=None,
            failure_code=None,
            sanitized_error_detail=None,
        )

    except GovernedEmbeddingAdapterError as exc:
        return CapabilityProbeResult(
            passed=False,
            observed_document_dimension=None,
            observed_query_dimension=None,
            observed_document_norm_min=None,
            observed_document_norm_max=None,
            observed_query_norm=None,
            document_evidence=None,
            query_evidence=None,
            failure_category="adapter_error",
            failure_code="governed_adapter_error",
            sanitized_error_detail=_sanitize_detail(str(exc)),
        )
    except Exception as exc:
        return CapabilityProbeResult(
            passed=False,
            observed_document_dimension=None,
            observed_query_dimension=None,
            observed_document_norm_min=None,
            observed_document_norm_max=None,
            observed_query_norm=None,
            document_evidence=None,
            query_evidence=None,
            failure_category="probe_exception",
            failure_code="unexpected_probe_error",
            sanitized_error_detail=_sanitize_detail(
                f"{type(exc).__name__}: {exc}"
            ),
        )
