/**
 * F1.6.1 — runtime-error sanitizer.
 *
 * SECURITY INVARIANT — the central gate against research-payload leakage:
 *   NEVER include raw error.message, error.stack, rejection reasons,
 *   request/response bodies, headers, or tokens in the report.
 *
 * Diagnostic utility comes ONLY from:
 *   - event_id (caller-supplied, generated by registry/reporter)
 *   - category (allowlisted enum)
 *   - normalized error_name (class name only, bounded)
 *   - route (pathname only — query/fragment stripped)
 *   - sanitized component_stack (paths and queries stripped from frames)
 *   - build_version
 *   - occurred_at (ISO timestamp)
 *
 * F1.6.1 [V3-2]: reportRuntimeError calls this synchronously. Sanitizer
 * must not throw — wrap any normalization failure in a try/catch and
 * return an allowlisted fallback.
 *
 * F1.6.1 [C4]: AbortError is NOT filtered here. The reporter layer
 * (lib/runtime-error-reporter.ts) decides whether to send. The sanitizer
 * is purely concerned with: "given we ARE sending, what is the safe
 * payload?". The reporter's pre-send gate filters AbortError.
 */

import type {
  ClientRuntimeErrorReport,
  RuntimeErrorCode,
} from "@/api/contracts/diagnostics";

// ── Field bounds (mirror backend Pydantic schema) ─────────────────────

export const MAX_EVENT_ID = 64;
export const MAX_ROUTE = 512;
export const MAX_COMPONENT_STACK = 4096;
export const MAX_ERROR_NAME = 128;
export const MAX_BUILD_VERSION = 64;
export const MAX_CORRELATION_ID = 128;
export const MAX_OCCURRED_AT = 64;

// ── Allowlisted messages per category (NEVER raw Error.message) ───────

export const ALLOWLISTED_MESSAGES: Record<RuntimeErrorCode, string> = {
  render_error: "A component failed while rendering.",
  lazy_route_error: "A route module could not be loaded.",
  global_error: "An unexpected browser error occurred.",
  unhandled_rejection: "An unexpected asynchronous error occurred.",
};

// ── Sanitization helpers ──────────────────────────────────────────────

/**
 * Sensitive substrings that must NEVER appear in any transmitted field.
 * Used as a final defense-in-depth sweep. The primary protection is that
 * we never put raw error.message/stack into any field in the first place;
 * this regex catches accidental leaks via component_stack frame paths
 * (which are bounded but could contain URLs).
 */
const SENSITIVE_PATTERNS: readonly RegExp[] = [
  // Bearer tokens (Authorization header values)
  /[Bb]earer\s+[A-Za-z0-9._~+/=-]+/g,
  // api_key / access_token / token query params
  /[?&](api_key|access_token|token|secret)=([^&#\s]+)/g,
  // credential-bearing URLs (user:pass@host)
  /:\/\/[^/\s:@]+:[^/\s:@]+@/g,
  // generic long hex/base64 strings that look like keys (>32 chars)
  /[Aa]uthorization:\s*[^\s]+/g,
];

/**
 * Strip credentials, query secrets, and bearer tokens from a string.
 * Replaces matches with a fixed redaction marker so the structure of
 * any stack frame remains readable for diagnosis.
 */
export function stripSensitiveValues(input: string): string {
  let out = input;
  for (const pattern of SENSITIVE_PATTERNS) {
    out = out.replace(pattern, "[REDACTED]");
  }
  return out;
}

/**
 * Reduce a component stack (the React-provided "in X\nin Y" trace) to a
 * bounded, sanitized form. The component NAMES are diagnostic; the
 * props/props-text in the stack (which React sometimes includes) are
 * not safe and are stripped.
 *
 * Component stacks look like:
 *     at ComponentName
 *     at ComponentName (file:///path/to/file.tsx:123:45)
 *     in ComponentName (created by ParentName)
 *
 * We keep the component-name lines, strip the file URIs down to the
 * filename only (no path, no query), strip any embedded props text,
 * and bound the total length.
 */
export function sanitizeComponentStack(raw: string | undefined | null): string | null {
  if (!raw) return null;
  try {
    const lines = raw.split("\n").map((line) => {
      // Strip sensitive values first (defense against embedded URLs/tokens).
      let cleaned = stripSensitiveValues(line);
      // Reduce file URIs to filename only.
      cleaned = cleaned.replace(
        /(\()?((?:https?|file):\/\/[^\s)]+?)(:\d+:\d+)?(\))?/g,
        (_m, p1, url, _loc, p2) => {
          const filename = url.split("/").pop() ?? url;
          return `${p1 ?? ""}${filename}${p2 ?? ""}`;
        },
      );
      // Truncate each line — long lines may include props text.
      return cleaned.length > 200 ? cleaned.slice(0, 200) + "…" : cleaned;
    });
    const joined = lines.join("\n");
    return joined.length > MAX_COMPONENT_STACK
      ? joined.slice(0, MAX_COMPONENT_STACK)
      : joined;
  } catch {
    return null;
  }
}

/**
 * Derive the top component frame from a component stack — used as a
 * deduplication fingerprint input. Returns the first component name
 * found, or "<no-stack>".
 */
export function topComponentFrame(componentStack: string | null | undefined): string {
  if (!componentStack) return "<no-stack>";
  const match = componentStack.match(/(?:at|in)\s+([A-Z][A-Za-z0-9_]+)/);
  return match?.[1] ?? "<no-stack>";
}

/**
 * Normalize an error's class name. Strips everything except ASCII
 * letters, digits, underscore — defense against log-injection via
 * crafted error names. Bounded to MAX_ERROR_NAME.
 *
 * Accepts any unknown thrown value:
 *   - Error instance → use .name
 *   - object with name property → use the name
 *   - string → use the string itself (treat it as a name)
 *   - anything else → typeof
 */
export function normalizeErrorName(error: unknown): string {
  try {
    let proto: string;
    if (error instanceof Error) {
      proto = error.name;
    } else if (typeof error === "string") {
      proto = error;
    } else if (typeof error === "object" && error !== null && "name" in error) {
      proto = String((error as { name: unknown }).name);
    } else {
      proto = typeof error;
    }
    const cleaned = proto.replace(/[^A-Za-z0-9_]/g, "");
    if (!cleaned) return "unknown";
    return cleaned.length > MAX_ERROR_NAME ? cleaned.slice(0, MAX_ERROR_NAME) : cleaned;
  } catch {
    return "unknown";
  }
}

/**
 * Reduce a route/location to pathname only. Strips ? and #. Bounded.
 */
export function sanitizeRoute(route: string | undefined | null): string {
  if (!route) return "";
  try {
    let r = route;
    for (const sep of ["?", "#"]) {
      const idx = r.indexOf(sep);
      if (idx >= 0) r = r.slice(0, idx);
    }
    // Defense against credentials in URL.
    r = stripSensitiveValues(r);
    return r.length > MAX_ROUTE ? r.slice(0, MAX_ROUTE) : r;
  } catch {
    return "";
  }
}

/**
 * Sanitize an event/correlation ID. ASCII alphanumeric + dash/underscore
 * only; bounded length.
 */
export function sanitizeId(value: string | null | undefined, max: number): string | null {
  if (!value) return null;
  try {
    const cleaned = value.replace(/[^A-Za-z0-9_-]/g, "");
    return cleaned ? (cleaned.length > max ? cleaned.slice(0, max) : cleaned) : null;
  } catch {
    return null;
  }
}

// ── Build the report ──────────────────────────────────────────────────

export interface SanitizerContext {
  category: RuntimeErrorCode;
  route: string;
  componentStack?: string;
  /** Optional correlation ID — typically captured from response headers. */
  correlationId?: string;
  /** Build version injected at compile time. */
  buildVersion?: string;
}

/**
 * Construct a sanitized ClientRuntimeErrorReport from an arbitrary
 * thrown value. NEVER throws — on any internal failure, returns a
 * minimal valid report with allowlisted fallbacks.
 *
 * F1.6.1 [V3-2]: the reporter generates the event_id and passes it in
 * (so it matches the registry's canonical event_id). The sanitizer does
 * NOT generate event_id.
 */
export function sanitizeErrorForReport(
  error: unknown,
  context: SanitizerContext,
  eventId: string,
): ClientRuntimeErrorReport {
  // Pre-validate the eventId — the registry generated it but defense.
  const safeEventId = sanitizeId(eventId, MAX_EVENT_ID) ?? "evt-fallback";

  return {
    schema_version: "client_runtime_error_v1",
    event_id: safeEventId,
    category: context.category,
    route: sanitizeRoute(context.route),
    component_stack: sanitizeComponentStack(context.componentStack),
    error_name: normalizeErrorName(error),
    // Always allowlisted per category — NEVER raw error.message.
    sanitized_message: ALLOWLISTED_MESSAGES[context.category] ?? "An unexpected error occurred.",
    correlation_id: sanitizeId(context.correlationId, MAX_CORRELATION_ID),
    build_version: sanitizeId(context.buildVersion ?? null, MAX_BUILD_VERSION),
    occurred_at: safeNow(),
  };
}

function safeNow(): string {
  try {
    return new Date().toISOString().slice(0, MAX_OCCURRED_AT);
  } catch {
    return "";
  }
}
